defaults: &defaults
    # Required.
    client_id: GITHUB_CLIENT_ID_HERE
    client_secret: GITHUB_SECRET_HERE
    authorization_server: https://github.com
    requested_scope: offline_access,user
    authorize_path: /login/oauth/authorize
    access_token_path: /login/oauth/access_token

development:
  <<: *defaults

test: &test
  <<: *defaults

production: &production
  <<: *defaults

# staging:
#   <<: *production
#
# cucumber:
#   <<: *test